use customer_behaviour_db;


-- Q2 What is the total reveneu generated by male vs. female customer?
select gender, SUM(purchase_amount) as revenue
from customer_behaviour
group by gender;

-- Q2 which customer used a discount but still spent more than average purchase amount?
select customer_id, purchase_amount
from customer_behaviour
where discount_applied ='Yes' and purchase_amount>=(select AVG(purchase_amount)from customer_behaviour);

-- Q3 which are the top 5 products with a highest average review rating?
select item_purchased, ROUND(AVG(review_rating),2) as "AVG product rating"
from customer_behaviour
group by item_purchased
order by AVG(review_rating) desc
limit 5;

-- Q4 compare the average purchase amounts between standard and Express shipping?
select shipping_type,
ROUND(AVG(purchase_amount),2) as 'AVG_purchase_amount'
from customer_behaviour
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- Q5 Do subscribed customer spend more? compare avg spend and total revenue between subscribers and non subscribers
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as'avg_spend',
ROUND(SUM(purchase_amount),2) as'total_revenue'
from customer_behaviour
group by subscription_status
order by total_revenue,  avg_spend desc;

-- Q6 which 5 product have the highest percentage with discounts applied?
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied ='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer_behaviour
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7 segment customers into new, returning , and loyal based on their total number
--    of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from customer_behaviour)
select customer_segment , count(*) as 'Number of Customers'
from customer_type
group by customer_segment;

-- Q8 what are the top 3 most purchased whthin each category?

with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count(customer_id)DESC) as item_rank
from customer_behaviour
group by category, item_purchased)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- Q9 are customers who are repeat buyes(more than 5 previous purchases ) also likely to subscribe?
 
select subscription_status,
count(customer_id) as repeat_buyers
from customer_behaviour
where previous_purchases>5
group by subscription_status;

-- Q10 what is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer_behaviour
group by age_group
order by total_revenue desc
















